framework:
    workflows:
        pre_delivery_order:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'statusId'
            supports:
                - App\Application\Service\StatusResolver\OrderStatusModel
            places:
                - '0'
                - '1'
                - '11'
                - '12'
                - '14'
                - '2'
                - '21'
                - '22'
                - '24'
                - '25'
                - '26'
                - '4'
                - '5'
                - '6'
                - '-1'
                - '-2'
            transitions:
                available_in_office_and_not_fully_confirmed_from_0:
                    guard: "subject.isAvailableInOfficeAndNotFullyConfirmedFromPlaced()"
                    from: '0'
                    to: '14'
                preparing_on_production_from_0:
                    guard: "subject.isPreparingOnProductionFromPlaced()"
                    from: '0'
                    to: '12'
                preparing_on_stock_from_0:
                    guard: "subject.isPreparingOnStockFromPlaced()"
                    from: '0'
                    to: '11'
                available_in_office_and_not_fully_confirmed_from_1:
                    guard: "subject.isAvailableInOfficeAndNotFullyConfirmed()"
                    from: '1'
                    to: '14'
                preparing_on_stock_from_1:
                    guard: "!subject.isPreparingOnProduction()"
                    from: '1'
                    to: '11'
                preparing_on_production_from_1:
                    guard: "subject.isPreparingOnProduction()"
                    from: '1'
                    to: '12'
                is_payment_time_expired_from_2:
                    guard: "subject.isSlotTimeExpiredAndPaid()"
                    from: '2'
                    to: '24'
                is_need_to_hurry_up_unpaid_from_2:
                    guard: "subject.isNeedToHurryToPayUnpaid()"
                    from: '2'
                    to: '21'
                is_slot_time_running_and_paid_2:
                    guard: "subject.isSlotTimeRunningAndPaid()"
                    from: '2'
                    to: '25'
                is_slot_time_expired_and_paid_2:
                    guard: "subject.isSlotTimeExpiredAndPaid()"
                    from: '2'
                    to: '26'
                has_paid_from_2:
                    guard: "subject.hasPaid()"
                    from: '2'
                    to: '22'
                check_out_status_to_5:
                    from: '4'
                    to: '5'
