parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Domain/ValueObject/'
            - '../src/Kernel.php'

    App\Infrastructure\EventListener\ExceptionListener:
        arguments:
            $env: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }