version: "3.8"

networks:
  status-resolver-net:
    name: status-resolver-net
    driver: bridge

services:
  php-fpm:
    container_name: php-fpm
    networks:
      - status-resolver-net
    build:
      context: ../../
      dockerfile: ./.deployment/docker/php-fpm/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ./../../:/var/www/status-resolver

  nginx:
    container_name: nginx
    networks:
      - status-resolver-net
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        PHP_UPSTREAM_CONTAINER: ${PHP_UPSTREAM_CONTAINER}
        PHP_UPSTREAM_PORT: ${PHP_UPSTREAM_PORT}
    environment:
      PHP_UPSTREAM_CONTAINER: ${PHP_UPSTREAM_CONTAINER}
      PHP_UPSTREAM_PORT: ${PHP_UPSTREAM_CONTAINER}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./../../:/var/www/status-resolver:rw
    depends_on:
      - php-fpm

  postgres:
    container_name: postgres
    networks:
      - status-resolver-net
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_status_resolver_data:/var/lib/postgresql/data:rw
volumes:
  db_status_resolver_data:
