version: "3.8"

networks:
  status-resolver-net:
    name: status-resolver-net
    driver: bridge
    external: true

services:
  php-fpm:
    container_name: php-fpm
    networks:
      - status-resolver-net
    build:
      context: ../../
      dockerfile: ./.deployment/docker/php-fpm/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ./../../:/var/www/status-resolver
