name: CI/CD Workflow

on:
  pull_request:
    branches: [master]
    types: [opened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker-compose build
          docker-compose up -d
          docker exec php-fpm composer install -o

  deploy_prod:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    env:
      SSH_PRIVATE_KEY_PROD: ${{ secrent.SSH_PRIVATE_KEY_PROD }}
      PROD_HOST: ${{ secrent.PROD_HOST }}
      PROD_DEPLOY_USER: ${{ secret.PROD_DEPLOY_USER }}
      CURRENT_DEPLOY_DIR: ${{ secret.CURRENT_DEPLOY_DIR }}
      PREVIOUS_DEPLOY_DIR: ${{ secret.PREVIOUS_DEPLOY_DIR }}
      DEPLOY_VARS_DIR: ${{ secret.DEPLOY_VARS_DIR }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to master
        run: |
          echo "Deploying to master server..."
          echo "$SSH_PRIVATE_KEY_PROD" > private_key
          chmod 600 private_key
          echo "Exec git pull"
          ssh -o StrictHostKeyChecking=no -i private_key $PROD_DEPLOY_USER@$PROD_HOST "cd $DEPLOY_VARS_DIR && git pull"
          echo "Exec composer install"
          ssh -o StrictHostKeyChecking=no -i private_key $PROD_DEPLOY_USER@$PROD_HOST "docker exec prod_php_fpm composer install"
          echo "Exec doctrine:migrations:migrate"
          ssh -o StrictHostKeyChecking=no -i private_key $PROD_DEPLOY_USER@$PROD_HOST "docker exec prod_php_fpm php bin/console doctrine:migrations:migrate --no-interaction"
        shell: bash
